# Generated by Django 5.2.3 on 2025-07-04 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_contralor_personero_profile_delete_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contralor',
            name='position',
        ),
        migrations.RemoveField(
            model_name='personero',
            name='position',
        ),
    ]
