# Generated by Django 5.2.3 on 2025-07-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_remove_contralor_position_remove_personero_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contralor',
            name='vote',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personero',
            name='vote',
            field=models.IntegerField(max_length=50),
        ),
    ]
