# Generated by Django 5.2.3 on 2025-07-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_contralor_vote_alter_personero_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contralor',
            name='vote',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='personero',
            name='vote',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
